# Generated by Django 4.1.1 on 2022-10-17 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotelroom',
            name='room_number',
        ),
        migrations.RemoveField(
            model_name='hotelroomimages',
            name='image',
        ),
        migrations.AddField(
            model_name='hotelroomimages',
            name='image_path',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='reservations',
            name='booking_id',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='phone_number',
            field=models.CharField(default='12345678', max_length=50),
        ),
        migrations.AlterField(
            model_name='hotelroom',
            name='room_status',
            field=models.BooleanField(default=False),
        ),
    ]
