# Generated by Django 4.1.2 on 2022-10-24 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_hotelroom_room_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotelroom',
            name='room_description',
            field=models.TextField(default='No description'),
        ),
        migrations.AddField(
            model_name='hotelroom',
            name='room_quantity',
            field=models.IntegerField(default=7),
        ),
    ]
