# Generated by Django 4.1.1 on 2022-10-20 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_username_users_usernames'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='usernames',
            new_name='username',
        ),
    ]
