# Generated by Django 4.1.1 on 2022-11-04 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_users_email_remove_users_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, default=None, max_length=150, null=True)),
                ('subject', models.TextField(blank=True, default=None, null=True)),
                ('message', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
    ]
