# Generated by Django 4.1.1 on 2022-11-05 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_hotelroom_stripe_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelroom',
            name='stripe_link',
            field=models.TextField(default=None, null=True),
        ),
    ]
