# Generated by Django 4.1.2 on 2022-11-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_hotelroom_stripe_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='end_date',
            field=models.DateField(default='1995-12-12'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='multiplier',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='reservations',
            name='start_date',
            field=models.DateField(default='1995-12-12'),
        ),
        migrations.DeleteModel(
            name='Payments',
        ),
    ]
